steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/api-pengirimanbarang", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/api-pengirimanbarang"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "api-pengirimanbarang"
      - "--image"
      - "gcr.io/$PROJECT_ID/api-pengirimanbarang"
      - "--timeout"
      - "1000s"
      - "--port"
      - "5000"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - >
        DB_HOST=34.55.111.115,
        DB_USER=root,
        DB_PASS=,
        DB_NAME=pengiriman_db,
        ENCRYPTION_KEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
        ENCRYPTION_IV=abcdefabcdefabcdefabcdefabcdefab

options:
  logging: CLOUD_LOGGING_ONLY